name: Демо работоспособности всех утилит

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cd build && make

      - name: "Лабораторная работа 1, п. 1"
        run: build/lr1_power 3 39

      - name: "Лабораторная работа 1, п. 1"
        run: build/lr1_power 2 30

      - name: "Лабораторная работа 1, п. 1"
        run: build/lr1_power 5 8

      - name: "Лабораторная работа 1, п. 2"
        run: build/lr1_ptr

      - name: "Лабораторная работа 1, п. 3"
        run: build/lr1_swp

      - name: "Лабораторная работа 2"
        run: build/lr2_matrix

      - name: "Лабораторная работа 3, п. 1"
        run: build/lr3_sort

      - name: "Лабораторная работа 3, п. 2"
        run: build/lr3_sort2

      - name: "Лабораторная работа 4, статические переменные"
        run: build/lr4_strings_static

      - name: "Лабораторная работа 4, malloc"
        run: build/lr4_strings_malloc

      - name: "Лабораторная работа 4, calloc"
        run: build/lr4_strings_calloc

      - name: "Лабораторная работа 4, array"
        run: build/lr4_strings_array

      - name: "Лабораторная работа 5, п. 1-3"
        run: (echo "lr5/file1.cpp" && echo search) | build/lr5_file1 && cat matches.txt

      - name: "Лабораторная работа 5, п. 4"
        run: build/lr5_file2 /home/dima/lr_cpp/lr5/test.txt /tmp/test2.txt && cat /tmp/test2.txt

      - name: "Лабораторная работа 5, п. 5-6"
        run: build/lr5_file3 "secret password" lr5/test.txt /tmp/test2.txt && build/lr5_file3 "secret password" /tmp/test2.txt /tmp/test3.txt && cat /tmp/test3.txt

      - name: "Лабораторная работа 6"
        run: build/lr6_main

